name: Validate Turtle Files with Apache Jena (riot)

on:
  push:
    paths:
      - 'TTL/**/*.ttl'
  pull_request:
    paths:
      - 'TTL/**/*.ttl'

jobs:
  validate:
    name: Turtle Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Apache Jena (riot)
        run: |
          curl -L -O https://downloads.apache.org/jena/binaries/apache-jena-5.4.0.tar.gz
          tar -xzf apache-jena-5.4.0.tar.gz
          echo "$PWD/apache-jena-5.4.0/bin" >> $GITHUB_PATH

      - name: Validate .ttl files with riot
        run: |
          echo "Running RDF syntax validation with riot..."
          FAIL=0
          for file in $(find . -name "*.ttl"); do
            echo "▶ Validating $file"
            riot --validate "$file"
            if [ $? -ne 0 ]; then
              echo "❌ Invalid Turtle: $file"
              FAIL=1
            else
              echo "✅ Valid: $file"
            fi
          done

          if [ $FAIL -ne 0 ]; then
            echo "❌ Some Turtle files failed validation."
            exit 1
          else
            echo "✅ All Turtle files are valid."
          fi
